#!/usr/bin/bash
# GNU bash, version 2.03.6(1)-release (i386-redhat-linux-gnu)
# $Id: mkdoc,v 1.5 2003-03-04 18:05:33 jabril Exp $
#
SECONDS=0 # Reset Timing
# Which script are we running...
L="####################"
{ echo "$L$L$L$L";
  echo "### RUNNING [$0]";
  echo "### Current date:`date`";
  echo "###"; } 1>&2;
#
### weaving and LaTeXing DOCUMENTATION
#
# Global Variables
# WORK is defined with "setcwd"...
BIN="$WORK/bin" ;
PARAM="$BIN/param" ;
DOCS="$WORK/docs" ;
DATA="$WORK/data" ;
TEST="$WORK/tests" ;
nwfile="gff2aplot" ;
export BIN PARAM DOCS DATA TEST nwfile ;
# extracting complementary material 
echo "Extracting \"$DOCS/AplotColorDefs.tex\"..." 1>&2 ;
no tangle -R"cmyk colors perl definition" $WORK/$nwfile.nw  | \
    $BIN/colors2tex.pl -d - | cpif $DOCS/tables/AplotColorDefs.tex ;
#
echo "Extracting PROGRAM VERSION..." 1>&2 ;
no tangle -R"Print Version" $WORK/$nwfile.nw | \
          cpif $BIN/getversion.pl ;
perl $BIN/getversion.pl | cpif $WORK/current_version ;
perl $BIN/getversion.pl -tex | cpif $DOCS/current_version.tex ;
echo "##### PROGRAM VERSION is "`cat $WORK/current_version` 1>&2 ;
#
echo "Extracting \"$DOCS/defs.tex\"..." 1>&2 ;
no tangle -R"HIDE: LaTeX aplot new definitions" $WORK/$nwfile.nw | \
         no weave -v -t4 -delay - | cpif $DOCS/defs.tex ;
echo "Extracting \"$DOCS/todo.tex\"..." 1>&2 ;
no tangle -R"HIDE: TODO" $WORK/$nwfile.nw | \
         no weave -v -t4 -delay - | cpif $DOCS/todo.tex ;
echo "Extracting \"$DOCS/localrefs.bib\"..." 1>&2 ;
no tangle -R"HIDE: BiBTeX references" $WORK/$nwfile.nw | \
         cpif $DOCS/localrefs.bib ;
#
echo "Extracting \"$DOCS/tables/GFF_regexes.tex\"..." 1>&2 ;
no tangle -R"HIDE: regular expressions for GFF-records" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/GFF_regexes.tex ;
#
echo "Extracting \"$DOCS/tables/CustomFile_parser_codes.tex\"..." 1>&2 ;
no tangle -R"HIDE: CustomFile parser codes" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/CustomFile_parser_codes.tex ;
echo "Extracting \"$DOCS/tables/GFF_parser_codes.tex\"..." 1>&2 ;
no tangle -R"HIDE: GFF parser codes" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/GFF_parser_codes.tex ;
echo "Extracting \"$DOCS/tables/missing_strands_substitution.tex\"..." 1>&2 ;
no tangle -R"HIDE: Missing strands substitution" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/missing_strands_substitution.tex ;
echo "Extracting \"$DOCS/tables/variable_definition_codes.tex\"..." 1>&2 ;
no tangle -R"HIDE: parameter2tex tags for latex commands" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/variable_definition_codes.tex ;
#
# Preparing variables and options descriptions for User's manual #'
echo "Extracting defs for MANUAL..." 1>&2 ;
no tangle -R"HIDE: new LaTeX definitions" $WORK/$nwfile.nw | \
         cpif $DOCS/mandefs.tex ;
echo "Extracting VARS/OPTIONS definitions for LaTeX files..." 1>&2 ;
no tangle -R"parameter2tex - LaTeX" $WORK/$nwfile.nw | \
         cpif $DOCS/tabledefs.tex ;
echo "Extracting COMMAND-LINE options for LaTeX files..." 1>&2 ;
no tangle -R"DESC command-line options" $WORK/$nwfile.nw | \
         $BIN/parameter2tex.pl -c -o $DOCS/tables/AplotCLopts.tex -- - ;
echo "Extracting CUSTOM-FILE variables for LaTeX files..." 1>&2 ;
no tangle -R"DESC custom file variables" $WORK/$nwfile.nw | \
         $BIN/parameter2tex.pl -v -o $DOCS/tables/AplotCFvars.tex -- - ;
#
# extracting color tables for the User's Manual #'
echo "Extracting \"$DOCS/AplotColorTbl.tex\"..." 1>&2 ;
no tangle -R"cmyk colors perl definition" $WORK/$nwfile.nw  | \
    egrep -v 'green|yellow|orange|red|brown' - | \
    $BIN/colors2tex.pl -t "violet" - | \
    cpif $DOCS/tables/AplotColorTbl.tex ;
echo "Extracting \"$DOCS/AplotColorTblCont.tex\"..." 1>&2 ;
no tangle -R"cmyk colors perl definition" $WORK/$nwfile.nw  | \
    egrep    'green|yellow|orange|red|brown' - | \
    $BIN/colors2tex.pl -t "yellow" - | \
    cpif $DOCS/tables/AplotColorTblCont.tex ;
# extracting page-size tables for the User's Manual #'
echo "Extracting \"$DOCS/AplotPageSizeTbl.tex\"..." 1>&2 ;
no tangle -R"page sizes perl definition" $WORK/$nwfile.nw | \
    $BIN/pagebbox2tex.pl - | cpif $DOCS/tables/AplotPageSizeTbl.tex ;
# extracting tables for the documentation
echo "Extracting \"$DOCS/tables/DataStructure_GFF.tex\"..." 1>&2 ;
no tangle -R"HIDE: GFF DATA STRUCTURE" $WORK/$nwfile.nw | \
         cpif $DOCS/tables/DataStructure_GFF.tex ;
#
#
MANUAL="GFF2APLOT_MANUAL";
pushd $DOCS/ ;
#
echo "### RUNNING LaTeX on $MANUAL.tex" 1>&2 ;
latex $MANUAL.tex ; 
latex $MANUAL.tex ; 
latex $MANUAL.tex ;
dvips $MANUAL.dvi -o $MANUAL.ps -t a4 ;
#
# echo "### CONVERTING PS to PDF: $MANUAL" 1>&2 ;
# ps2pdf $MANUAL.ps $MANUAL.pdf ;
#
#
# echo "### 2 PAGES x PAGE SMALL MANUAL: $MANUAL" 1>&2 ;
# ps2ps -sPAPERSIZE=a4 $MANUAL.ps $MANUAL.eps; mpage -vkT2 -bA4 -t $MANUAL.eps > $MANUAL.small.ps~; ps2ps -sPAPERSIZE=a4 $MANUAL.small.ps~ $MANUAL.small.ps
echo "### RUNNING psnup on $MANUAL.ps -> $MANUAL.small.ps" 1>&2 ;
psnup -pa4 -Pa4 -d -2 -m0.25cm $MANUAL.ps $MANUAL.small.ps
popd ;
{ echo "###"; echo "### Execution time for [$0] : $SECONDS secs";
  echo "$L$L$L$L";
  echo ""; } 1>&2;
#
exit 0
