#!/usr/bin/bash
# GNU bash, version 2.03.6(1)-release (i386-redhat-linux-gnu)
# $Id: nw2tex,v 1.1 2001-08-21 14:54:21 jabril Exp $
#
SECONDS=0 # Reset Timing
# Which script are we running...
L="####################"
{ echo "$L$L$L$L";
  echo "### RUNNING [$0]";
  echo "### Current date:`date`";
  echo "###"; } 1>&2;
# weaving and LaTeXing
# Global Variables
WORK="$HOME/development/softjabril/gfftools/gff2aplot" ;
BIN="$WORK/bin" ;
PARAM="$BIN/param" ;
DOCS="$WORK/docs" ;
DATA="$WORK/data" ;
TEST="$WORK/tests" ;
nwfile="gff2aplot" ;
export WORK BIN PARAM DOCS DATA TEST nwfile ;
# extracting complementary material 
echo "Extracting \"$DOCS/defs.tex\"..." ;
notangle -R"LaTeX deploy new definitions" $WORK/$nwfile.nw \
         > $DOCS/defs.tex ;
echo "Extracting \"$DOCS/AplotCLoptions.tex\"..." ;
notangle -R"LATEX command-line" $WORK/$nwfile.nw \
         > $DOCS/tables/AplotCLoptions.tex ;
echo "Extracting \"$DOCS/AplotCLoptionsTbl.tex\"..." ;
notangle -R"LATEX command-line table" $WORK/$nwfile.nw \
         > $DOCS/tables/AplotCLoptionsTbl.tex ;
echo "Extracting \"$DOCS/AplotCustomVars.tex\"..." ;
notangle -R"LATEX custom-vars" $WORK/$nwfile.nw  \
         > $DOCS/tables/AplotCustomVars.tex ;
echo "Extracting \"$DOCS/AplotCustomVarsTbl.tex\"..." ;
notangle -R"LATEX custom-vars table" $WORK/$nwfile.nw  \
         > $DOCS/tables/AplotCustomVarsTbl.tex ;
echo "Extracting \"$DOCS/AplotColorDefs.tex\"..." ;
notangle -R"LATEX cmyk colors" $WORK/$nwfile.nw  \
         > $DOCS/tables/AplotColorDefs.tex ;
echo "Extracting \"$DOCS/AplotColorTbl.tex\"..." ;
notangle -R"LATEX colors table" $WORK/$nwfile.nw  \
         > $DOCS/tables/AplotColorTbl.tex ;
echo "Extracting \"$DOCS/AplotPageSizeTbl.tex\"..." ;
notangle -R"LATEX page format table" $WORK/$nwfile.nw \
         > $DOCS/tables/AplotPageSizeTbl.tex ;
echo "Extracting \"$DOCS/DataStructure_GFF.tex\"..." ;
notangle -R"GFF DATA STRUCTURE" $WORK/$nwfile.nw \
         > $DOCS/tables/DataStructure_GFF.tex ;
# extracting main documentation
echo "Weaving \"$DOCS/$nwfile.tex\"..." ;
noweave -t4 -delay -x $WORK/$nwfile.nw > $DOCS/$nwfile.tex ;
# LaTeXing 
echo "LaTeXing \"$DOCS/$nwfile.tex\"..." ;
pushd $DOCS/ ;
latex $nwfile.tex ;
dvips $nwfile.dvi -o $nwfile.ps -t a4 ;
popd;
{ echo "###"; echo "### Execution time for [$0] : $SECONDS secs";
  echo "$L$L$L$L";
  echo ""; } 1>&2;
#
exit 0
