#!/usr/bin/bash
# GNU bash, version 2.03.6(1)-release (i386-redhat-linux-gnu)
# $Id: nw2tex,v 1.4 2002-12-24 13:53:58 jabril Exp $
#
SECONDS=0 # Reset Timing
# Which script are we running...
L="####################"
{ echo "$L$L$L$L";
  echo "### RUNNING [$0]";
  echo "### Current date:`date`";
  echo "###"; } 1>&2;
#
### weaving and LaTeXing
#
# Global Variables
# WORK is defined with "setcwd"...
BIN="$WORK/bin" ;
PARAM="$BIN/param" ;
DOCS="$WORK/docs" ;
DATA="$WORK/data" ;
TEST="$WORK/tests" ;
nwfile="gff2aplot" ;
export BIN PARAM DOCS DATA TEST nwfile ;
# extracting complementary material 
echo "Extracting \"$DOCS/defs.tex\"..." 1>&2 ;
no tangle -R"HIDE: LaTeX aplot new definitions" $WORK/$nwfile.nw | \
         no weave -v -t4 -delay - | cpif $DOCS/defs.tex ;
echo "Extracting \"$DOCS/todo.tex\"..." 1>&2 ;
no tangle -R"HIDE: TODO" $WORK/$nwfile.nw | \
         no weave -v -t4 -delay - | cpif $DOCS/todo.tex ;
echo "Extracting \"$DOCS/localrefs.bib\"..." 1>&2 ;
no tangle -R"HIDE: BiBTeX references" $WORK/$nwfile.nw | \
         cpif $DOCS/localrefs.bib ;
#
echo "Extracting \"$DOCS/tables/GFF_regexes.tex\"..." 1>&2 ;
no tangle -R"HIDE: regular expressions for GFF-records" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/GFF_regexes.tex ;
#
echo "Extracting \"$DOCS/tables/CustomFile_parser_codes.tex\"..." 1>&2 ;
no tangle -R"HIDE: CustomFile parser codes" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/CustomFile_parser_codes.tex ;
echo "Extracting \"$DOCS/tables/GFF_parser_codes.tex\"..." 1>&2 ;
no tangle -R"HIDE: GFF parser codes" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/GFF_parser_codes.tex ;
echo "Extracting \"$DOCS/tables/missing_strands_substitution.tex\"..." 1>&2 ;
no tangle -R"HIDE: Missing strands substitution" $WORK/$nwfile.nw | \
      no weave -v -delay - | cpif $DOCS/tables/missing_strands_substitution.tex ;
#
# extracting main documentation
echo "Weaving \"$DOCS/$nwfile.tex\"..." ;
no weave -v -t4 -delay -index -filter 'elide "HIDE: *"' \
        $WORK/$nwfile.nw | cpif $DOCS/$nwfile.tex ;
# LaTeXing 
echo "LaTeXing \"$DOCS/$nwfile.tex\"..." ;
pushd $DOCS/ ;
latex $nwfile.tex ;
dvips $nwfile.dvi -o $nwfile.ps -t a4 ;
popd;
{ echo "###"; echo "### Execution time for [$0] : $SECONDS secs";
  echo "$L$L$L$L";
  echo ""; } 1>&2;
#
exit 0
