#!/usr/bin/bash
# GNU bash, version 2.03.6(1)-release (i386-redhat-linux-gnu)
# $Id: ltx,v 1.2 2001-06-05 15:25:35 jabril Exp $
#
SECONDS=0 # Reset Timing
# Which script are we running...
L="####################"
{ echo "$L$L$L$L";
  echo "### RUNNING [$0]";
  echo "### Current date:`date`";
  echo "###"; } 1>&2;
# only LaTeXing
# Global Variables
export WORK="$HOME/development/sggp" ;
export BIN="$WORK/bin" ;
export LIB="$WORK/lib" ;
export DOCS="$WORK/docs" ;
export DATA="$WORK/data" ;
export nwfile="SintenicGenePrediction" ;
pushd $DOCS/ ;
latex $nwfile.tex ; 
latex $nwfile.tex ; 
latex $nwfile.tex ;
dvips $nwfile.dvi -o $nwfile.ps -t a4 ;
popd ;
{ echo "###"; echo "### Execution time for [$0] : $SECONDS secs";
  echo "$L$L$L$L";
  echo ""; } 1>&2;
#
exit 0
