#! /usr/local/bin/gawk -f 
# rgs, sb 1998 
# ccsr2gff converts an hsp file to a gff file


BEGIN{
  # default sequence name, override by geneid2ff seqname="seqname"
  seqname="NONAME";
  
  # default source name
  feature="hsp"; #overriden by feature="feature"
  
  # --- data structure -------------------------------------------------
  n_ffields =  18;  # number of fixed fields
  program =  1;  
  db      =  2;
  start   =  3; # hsp start in query
  end     =  4; # hsp end in query
  strand  =  5; # query strand
  frame   =  6; # query frame
  score   =  7; # hsp scores
  bits    =  8; 
  expect  =  9;
  prob    = 10; 
  sim     = 11;
  iden    = 12; # sim score
  locus   = 13; # locus name hit
  start_s = 14; # hsp start in query
  end_s   = 15; # hsp end in query
  strand_s= 16; # query strand
  frame_s = 17; # query frame
  lseq_s  = 18;
  # --- end data structure ----------------------------------------------

  # gff formatted output
  gff_format="%-10s %-10s %-10s %9d %9d %d  %1s  %1d  %s\n";
}
{
  if (!group) {
    gsub(/\|/,"_",$locus);
    group_=$locus;
  }
  else
    group_=group;

  source = $program "." $db;
  printf gff_format, seqname, source, feature,  $start,$end,  $score, $strand, $frame, group_;

}
