#!/bin/bash

log=/home/ug/ogonzalez/scripts/_LOGS/backup_m1-`date +%Y%m%d-%H%M`
data=`date +"%d %b %Y - %H:%M"`

echo $data >$log
echo >>$log

#`dirname $0`/backup_m1.1 >/dev/null 2>>$log
`dirname $0`/backup_m1.1 >>$log 2>&1

mail -s"backup_m1 $data" ogonzalez@imim.es <$log

# comprimeixo el fitxer nou i esborro els antics
cd `dirname $log`
chown ogonzalez:users $log
gzip $log
ls -t1 backup_m1* | tee /tmp/backup_m1.1 | head -10 >/tmp/backup_m1.2
rm -f `diff /tmp/backup_m1.[12] | grep '^<' | cut -c3-` /tmp/backup_m1.[12]
