#!/bin/bash

# per convertir allo que ens interessi a la blastmachine

# es bastant manual: les bases de dades no son gaire iguals entre si


# crea un directori a la BM de manera recursiva
pbmkdir() {
   unset direc
   for i in `echo $1 | tr "/" " "`
   do
      direc=$direc/$i
      pb mkdir $direc >/dev/null
   done
}


# aixo rep una llista de fitxers i els encadena i els passa a la BM
# a un directori igual al d'origen
# PER ARA CREO LA BDD SI NO EXISTEIX JA, PERO AQUEST *NO* ES UN BON CRITERI!!
# S'HAURIA DE FER NOMES SI HA CANVIAT: CALCULANT MD5SUM DELS FITXERS!!!
formatbm() {
   echo "Creant $1"
   if [ "`pb ls $1`" != "No matches." ]
   then
      echo "   IGNORAT: JA EXISTEIX"
      return
   fi
   pushd `pwd` >/dev/null
   direc=`dirname $1`
   base=`basename $1`
   cd $direc
   llista=$base*.dat.gz
   pack=/home/bdadmin/`echo $llista | md5sum | cut -c1-32`
   typeset -i num1 num2
   num1=0
   num2=`echo $llista | wc -w`
   rm -rf $pack 2>/dev/null
   for nom in $llista
   do
      let num1=num1+1
      printf "\r%50s\r   gunzip $nom ($num1/$num2) "
      zcat $nom | /home/ug/ogonzalez/scripts/FileToFasta.pl >>$pack
   done
   printf "\r%50s\r   gunzip OK ($num1/$num2)\n   formatdb... "
   pbmkdir $direc
   pb formatdb -p F -i $pack -n $direc/$base
#   rm $pack
   echo OK
   popd >/dev/null
}


if [ `whoami` != bdadmin ]
then
   echo "NOMES BDADMIN POT FER AIXO!!!"
   exit
fi
if [ ! -d /home/bdadmin ]
then
   echo "BDADMIN NO TE HOME LOCAL!!!"
   exit
fi

#### EMBL: totes les BDD; format EMBL
ls -1 /seq/databases/embl/release/*.dat.gz | sed 's/[0-9]*.dat.gz//' |
   uniq | while read bdd
do
      formatbm $bdd
done

#### SWISS-PROT: 
