#!/bin/bash

# per convertir allo que ens interessi a la blastmachine

# es bastant manual: les bases de dades no son gaire iguals entre si


# aixo rep una llista de fitxers i els encadena i els passa a la BM
# a un directori igual al d'origen
formatbm() {
   echo "Creant $direc/$base$primer-$darrer ($total bytes)"
   pack=`echo $llista | md5sum | cut -c1-32` # per evitar sobreescriure res
   typeset -i num1 num2
   num1=1
   num2=`echo $llista | wc -w`
   rm -rf /home/bdadmin/$pack 2>/dev/null
   for nom in $llista
   do
      printf "\r%50s\r   gunzipant $nom ($num1/$num2) "
      zcat $nom | /home/ug/ogonzalez/scripts/FileToFasta.pl >>/home/bdadmin/$pack
   done
   printf "\r%50s\r   formatejant... "
   pushd $direc
   cd /home/bdadmin
   pb formatdb -p F -i $pack -n $direc/$base$primer-$darrer
   rm $pack
   popd
   echo OK
}


if [ `whoami` != bdadmin ]
then
   echo "NOMES BDADMIN POT FER AIXO!!!"
   exit
fi
if [ ! -d /home/bdadmin ]
then
   echo "BDADMIN NO TE HOME LOCAL!!!"
   exit
fi

#### EMBL human: 55 fitxers, 2 Gb gz, 18 Gb descomprimit
####             encadenem els fitxers en blocks de 500 Mb comprimits
####             en format EMBL
direc=/seq/databases/embl/release
base="est_hum"
typeset -i index total long
index=1
total=0
llista=""
primer="01"
cd $direc
while :
do
   fitxer=`printf "%02i" $index`
   nom="$base$fitxer.dat.gz"
   if [ ! -e $nom ]
   then
      formatbm
      break
   fi
   long=`ls -l $nom | awk '{ print $5 }'`
   if (( total+long > 500000000 ))
   then
      formatbm
      llista=$nom
      let total=$long
      primer=$fitxer
   else
      llista="$llista $nom"
      let total=total+long
   fi
   darrer=$fitxer
   let index=index+1
done


