#!/bin/bash

# COMPTE: els directoris especificats a mkisofs es converteixen en / del
# CD creat, NO en directoris de primer nivell. El mes sensat es donar un
# sol directori que contingui tot el que volem gravar. Per aixo per ara
# nomes accepto un parametre

# A icarus es grava a 4x, la gravadora es "1,1,0" i la lectora es "1,0,0"

# A basileia es grava a 8x, la gravadora es "1,0,0" i la lectora es "1,1,0"

# les imatges es creen a /mnt/dosd/cd-images

# Crea la imatge amb el nom del directori que especifiquem. Aquest nom es
# fara servir tambe con a etiqueta de volum. Si el nom ja existeix, no pot
# continuar

error=0
if [ $# != 1 -o ! -s $1 ]
then
   echo "ERROR: cd1 <directorio>"
   exit
fi

direc=/home/cd_images
imatge=$direc/$1.iso
txt=$direc/$1.txt

if [ -s $imatge ]
then
   echo ERROR: $imatge ja existeix
   exit
fi

# creem una etiqueta que nomes contingui "A-Z0-9_" i un maxim d'onze chars
etiq=`echo $1 | tr a-z A-Z | tr -cd A-Z0-9_ | awk '{ print substr($0,0,11) }'`

echo Creant $imatge...

# -r : Rock Ridge amb UID=0, GID=0, chmod=555
# -J : Joliet
# -L : els noms poden comencar per "."
# -l : permet noms ISO9660 (no Joliet) de 31 caracters
# -f : no crea links simbolics, sino que segueix el link
# -split-output : particionar en fitxers d'1 Gb (per FAT32 i tal)
if (( `du -s $1 | awk '{ print $1 }'` > 750000 )) # es mes gran que 1 CD ==> es DVD i fem split
then
   splitoutput="-split-output"
fi
mkisofs -V"$etiq" -r -J -L -l -f $splitoutput -o $imatge $1 >$txt 2>&1 &

while [ `ps | grep -c mkisofs` != 1 ]
do
   sleep 1 # esperare fins que s'arrenqui el mkisofs
done

while [ `ps | grep -c mkisofs` = 1 ]
do
   while [ -s $txt -a `tail -1 $txt | grep -c 'estimate finish'` = 1 ]
   do
      echo -n `tail -1 $txt`
   done
done

echo
rm $txt
