#!/bin/bash

# per fer imatge d'un CD o DVD

# ho faig per la gravadora a eidolon: /dev/cdrom1

mida() {
   valor=$1
   if [ "$valor" = "" ]
   then
      valor=0
   fi
   while [ `echo $valor. | egrep -c '[0-9][0-9][0-9][0-9]\.'` = 1 ]
   do
      tmp=${valor%%???.*}
      valor=$tmp.${valor#$tmp}
   done
   printf "\r$imatge %14s " ${valor%.}
}

nom_unic=/tmp/`head -c 100 /dev/random | md5sum - | cut -c1-32`
imatge=/home/cdimages/imatge.iso
rm -rf $nom_unic
( dd if=/dev/cdrom1 of=$imatge ; touch $nom_unic ) &

while [ ! -e $nom_unic ]
do
   mida `ls -l $imatge | awk '{ print $5 }'`
   sleep 5
done
echo
rm $nom_unic
