#!/bin/bash

# extreu audio amb -Oraw per no tenir el "header" de 44 bytes, ja que a
# cdrecord no li agrada
#
# COMPTE: NO HI HA CAP TIPUS DE CONTROL D'ERRORS!!

pistes=""
while [ $# != 0 ]
do
   pistes=$pistes" "$1
   shift
done

cdda="cdda2wav -D/dev/cdrom -H -P4 -v0 -I cooked_ioctl -x"
if [ "$pistes" = "" ]
then
   $cdda -B
else
   set `echo $pistes`
   while [ $# != 0 ]
   do
      tot="0$1"
      inic=${tot%??}
      pista=${tot#$inic}
      $cdda -t$1 track$pista.wav
      shift
   done
fi
