#!/bin/bash

# potser el Xavi ja va fer un script per fer aixo, pero ja el buscare

# comprovo els directoris on "mirror" ha ficat coses, per assegurar que
# tots els gz son complets. M'he trobat amb molts que no han baixat sencers,
# pero mirror posa la data de download i no la del original, aixi que la
# seguent vegada creu que son mes nous i no els torna a baixar tot i no ser
# complets

# NOMES POT CORRER COM A ROOT!! (sino, no hi ha access a "packages")

echo

for i in \
   `grep local_dir /usr/local/Install/mirror/packages/ftp.embnet.cnb.uam.es | \
   awk -F= '{ print $2 }'`
do
   echo $i
   cd $i
   find . 2>/dev/null | grep -i -e \.gz$ -e \.z$ -e \.zip$ >/tmp/checkgz.lst
   total=`wc -l </tmp/checkgz.lst | tr -d " "`
   if [ $total = 0 ]
   then
      echo "   Res a revisar"
   else
      typeset -i actual
      actual=1
      while read j
      do
         echo -n "   $j "
         long=`ls -lh $j | awk '{ print $5 }'`
         nom=${j%.*}
         ext=${j#$nom}
         echo -n \(${long}b, $actual/$total\)...\ 
         if [ $ext = ".zip" ]
         then
            unzip -t $j 1>/dev/null 2>&1
         else
            gunzip -t $j 1>/dev/null 2>&1
         fi
         if [ $? = 0 ]
         then
            echo OK
         else
            echo "---> ERROR!!! <---"
         fi
         let actual=actual+1
      done </tmp/checkgz.lst
   fi
   echo
done

rm /tmp/checkgz.lst
