#!/bin/bash

# aixo es per casos com el genoma de rata, juny del 2003: database conte
# els fitxers gzipats i no gzipats
#
# si el .txt.gz es el mateix fitxer que el .txt, esborro el .txt; si no,
# mantinc ambdos i es revisa manualment que fer-ne
#
# ho fem no recursivament al directori actual, i nomes busquem .txt.gz

for nom in *.txt.gz
do
   nom2=${nom%.gz}
   if [ -e $nom2 ]
   then
      gunzip --stdout $nom | diff -q - $nom2 >/dev/null 2>&1
      if [ $? = 2 ]
      then
         echo "**Problemes amb $nom"
      elif [ $? = 1 ]
      then
         echo "--Revisar $nom: diferencies .txt.gz/.txt"
      else
         echo "  $nom2 esborrat"
         rm $nom2
      fi
   fi
done
