#!/bin/bash

# faig md5sum de tot el que trobo, per comparar-lo amb el d'un altre
# directori

ls -AR1 | grep -v ^$ | while read fitxer
do
   inici=${fitxer%?}
   final=${fitxer#??}
   if [ "${fitxer#$inici}" = ":" ]
   then
      path=${final%?}
   else
      if [ "$path" != "" ]
      then
         fitxer=$path/$fitxer
      fi
      if [ -f "$fitxer" ]
      then
         md5sum "$fitxer"
      elif [ -d "$fitxer" ]
      then
         echo "   es un directori                $fitxer"
      else
         echo "      fitxer no revisable         $fitxer"
      fi
   fi
done
