#!/usr/bin/perl

# despres de fer un "cp -afuv" per duplicar el directori del web,
# executem aixo per eliminar aquells fitxers que tambe hagin
# estat eliminats de l'original
#
# la rutina funciona de manera recursiva des del directori
# proporcionat com a parametre
#
# log:
#    d significa eliminat
#    . significa que no ha canviat
# majuscules per direcs, minuscules per fitxers


use File::Path;

# primer parametre: directori original
# segon parametre: copia
sub direc {

   my $original=$_[0];
   opendir(DIR,"$original");
   my @dirorig=sort(grep(!/^(\.|\.\.)$/,readdir(DIR)));
   closedir(DIR);
   my $ultim=-1;
   for ( $j=0 ; $j<=$#dirorig ; $j++ ) {
      if ( -d "$original/$dirorig[$j]" ) {
         $ultim=$j;
      }
   }

   my $copia=$_[1];
   opendir(DIR,"$copia");
   my @dircopia=sort(grep(!/^(\.|\.\.)$/,readdir(DIR)));
   closedir(DIR);

   my $tree=$_[2];
   $original =~ m#/[^/]+$#;
   $direc=$&;
   $direc =~ s#/##;
   if ( $tree ne "" ) {
      for ( $j=0 ; $j<length($tree) ; $j++ ) {
         $tipus=substr($tree,$j,1);
         if ( $tipus eq "1" ) { # directori obert
            print "|";
         } elsif ( $tipus eq "2" ) { # final directori obert
            print "`";
            substr($tree,$j,1)="0";
         } else {
            print " ";
         }
         if ( $j == length($tree)-1 ) {
            print "-- ";
         } else {
            print "   ";
         }
      }
   }
   print "$direc\n";

   $noesborrat=0;
   $esborrat=0;
   for ( my $i=0 ; $i<=$#dircopia ; $i++ ) {
      $nom=$dircopia[$i];
      $nom =~ s/([\+\.\(\)\|\[\]\$\^])/\\$1/og;
      if ( grep(/^$nom$/,@dirorig) ) {
         $noesborrat++;
         if ( -d "$original/$nom" ) {
            if ( $ultim != $i ) {
               $nou="1";
            } else {
               $nou="2";
            }
            &direc("$original/$nom","$copia/$nom",$tree.$nou);
         }
      } else {
         $esborrat++;
#        rmtree("$copia/$nom");
         print "$nom\n";
      }
   }

#  print ": $noesborrat OK, $esborrat esborrats\n";

}

$original="/usr/local";
$copia="/home2/__backup_usr_local__";
$tree=""; # per cada nivell poso 1 si hi ha linia, 2 si final, 0 si res
print "Per ara la linia que copia esta comentada ==> fes-ho a ma!!\n";
#system("cp -afuv $original $copia >$copia/log.out 2>$copia/log.err");
print "Per ara la linia que esborra esta comentada!!\n";
&direc("$original","$copia",$tree);

