#!/bin/bash

# envio una linia a cada terminal oberta, per veure qui es qui
# (util, per exemple, quan vull fer un kill d'un ssh que s'ha quedat
# penjat i no se quin es el que he de matar)

# no envio res a la terminal actual: aquest no esta penjada!!

# amb -s fa un sleep d'1 segon entre echo i echo (per parar-lo si
# ja em trobat el que buscavem sense enviar mes porqueria a altres
# terminals

actual=`ps --no-headers | grep "^ *$$ " | cut -d" " -f 2`

ps -u `id -u` -o tty | sort -u | grep pts | while read tty
do
   if [ "$actual" != "$tty" ]
   then
      echo -n "${tty#pts/} "
      echo $tty >/dev/$tty
      if [ "$1" = "-s" ]
      then
         sleep 1
      fi
   fi
done
echo
