#!/bin/bash

hores=0
minuts=0
segons=0

while [ `mount|grep -c usbdrive` == 1 ]
do
   sleep 1
   let segons=segons+1
   if (( segons > 59 ))
   then
      segons=0
      let minuts=minuts+1
      if (( minuts > 59 ))
      then
         minuts=0
         let hores=hores+1
      fi
   fi
   printf "\r%s" "Esperant autoumount: `date -d $hores:$minuts:$segons +%H:%M:%S` "
done
echo "- OK"
