#!/usr/bin/perl

# Esborro de STDIN els .listing, els "is more recent, not retrieving" i
# els "md5.sum", i nomes guardo la primera i la darrera linies de punts
# de cada "download"


@mirror=<STDIN>;

for ( $i=0;$i<=$#mirror;$i++) {
   if ( $mirror[$i] =~ /^--\d\d:\d\d:\d\d-- / &&
        $mirror[$i+1] =~ /^ .+ => .+\/\.listing\'$/ ) {
      if ( $i > 0 && $mirror[$i-1] =~ /^The sizes do not match.*retrieving\.$/ ) {
         $i--
      }
      for ( $j=$i+2;$j<=$#mirror;$j++) {
         if ( $mirror[$j] =~ /^--\d\d:\d\d:\d\d--/ ||
              $mirror[$j] =~ /^Local file.+not retrieving\.$/ ||
              $mirror[$j] =~ /^FINISHED/ ) {
            last;
         }
      }
      splice(@mirror,$i,$j-$i);
      $i--;
   } elsif ( $mirror[$i] =~ / is more recent, not retrieving\.$/ ) {
      splice(@mirror,$i--,2);
   } elsif ( $mirror[$i] =~ /^--\d\d:\d\d:\d\d--.+\/md5.sum$/ &&
             $mirror[$i+1] =~ /^\s+=> .+\/md5.sum\'$/ ) {
      for ( $j=$i+2;$j<=$#mirror;$j++) {
         if ( $mirror[$j] =~ /^--\d\d:\d\d:\d\d--/ ) {
            last;
         }
      }
      splice(@mirror,$i,$j-$i);
      $i--;
   } elsif ( $mirror[$i] =~ /^\s*\d+K -> \.+.+$/ ) {
      for ( $j=$i+2;$j<=$#mirror;$j++) {
         if ( $mirror[$j] =~ /^$/ ) {
            last;
         }
      }
      splice(@mirror,$i+1,$j-$i-2);
      $i+=2;
   }
}

print @mirror;
