#!/usr/bin/perl

# per filtrar el log d'apolo: te massa entrades de pop3 i smtp (rode i moi)
# i revisar-lo tot es una perdua de temps. i un conyas.
#
# revisa oSYSLOG i SYSLOG com si fossin un sol fitxer
#
# afegeix oSYSLOG a /root/SYSLOG i mou SYSLOG a oSYSLOG. no perdem historic
# de logs, simplement el movem de /var/adm a /root.  cada cert temps hauria
# de fer neteja de /root/SYSLOG: no vull un historic massa gran. PERO AIXO
# NO ESTA FET ENCARA!!!
#
# algunes de les coses que vull revisar inclouen varies linies, aixi que pot
# ser que quedin incompletes en fer els canvis de nom dels SYSLOG i provocar
# llavors que algunes entrades no quedin ben filtrades
#
# coses que vull mirar:
#
#    gnu-pop3d: 4 linies del rode
#
#       gnu-pop3d[PID]: connect from 45.red-213-96-48.pooles.rima-tde.net
#       gnu-pop3d[PID]: Incoming connection opened
#       gnu-pop3d[PID]: User 'rguigo' logged in with mailbox 'rguigo'
#       gnu-pop3d[PID]: Session ended for user: rguigo
#
#    gnu-pop3d: 4 linies del moi
#
#       gnu-pop3d[PID]: connect from fpuigvert.cesca.es
#       gnu-pop3d[PID]: Incoming connection opened
#       gnu-pop3d[PID]: User 'mburset' logged in with mailbox 'mburset'
#       gnu-pop3d[PID]: Session ended for user: mburset
#
#    sendmail: 1 linia, jupiter o basquet
#
#       sendmail[PID]: connect from <servidor>.imim.es
#
#    ssh: n linies, algunes d'elles apareixen o no en funcio de la situacio
#
#         la primera es sempre "PAM _pam_init_handlers". mes endavant, i potser
#         despres d'alguna linia del mateix PID, apareix "accepted password for"
#         o "failed (password|none|keyboard-interactive...) for"
#
#         la darrera es "session closed for", "connection closed by", "timeout before",
#         "received disconnect from". aparentment, "connection closed" pot no ser la
#         darrera i anari llavors seguida per "n more authentication failure"
#
#       sshd[PID]: PAM _pam_init_handlers: no default config /etc/pam.d/other
#       sshd(pam_unix)[PID]: authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=<maquina>  user=<usuari>
#       sshd[PID]: Failed password for <usuari> from <maquina> port <port> ssh2
#       sshd[PID]: Failed none for <usuari> from <maquina> port <port> ssh2
#       sshd[PID]: Failed keyboard-interactive for <usuari> from <maquina> port <port> ssh2
#       sshd[PID]: Received disconnect from <maquina>: 13: Authentication cancelled by user.
#       sshd[PID]: Accepted password for <usuari> from <maquina> port <port> ssh2
#       sshd[PID]: subsystem request for sftp
#       sshd(pam_unix)[PID]: session opened for user <usuari> by (uid=0)
#       sshd(pam_unix)[PID]: session closed for user <usuari>
#       sshd[PID]: Connection closed by <maquina>
#       sshd(pam_unix)[PID]: 1 more authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=<maquina>  user=<usuari>
#       sshd[PID]: fatal: Timeout before authentication for <maquina>.
#
#    telnet:
#
#       telnetd[PID]: refused connect from <maquina>
#       telnetd[PID]: connect from <maquina>
#
#    login:
#
#       login[PID]: ?@<maquina> as <usuari>


if ( -e "oSYSLOG" ) {
   open(FIT,"oSYSLOG");
   @log=<FIT>;
   close(FIT);
}
if ( -e "SYSLOG" ) {
   open(FIT,"SYSLOG");
   push(@log,<FIT>);
   close(FIT);
}

# comenco eliminant a ma algunes linies que per algun motiu es repeteixin
# massa. ES COMPLETAMENT MANUAL!!!
# aixo pot ser una mica lent fet d'aquesta manera si hi ha massa linies, pero
# tampoc passa tan sovint com perque sigui un problema
$manual[0]="tps1d1 <6>Drive diagnostic failure: code 0x2\$";
$manual[1]="ALERT: tps1d1 Hardware error, Non-recoverable\$";
$manual[2]="unix: WARNING: RPC: host 193.146.190.133 down\$";
foreach $j (@manual) {
   @log=grep( ! /$j/ , @log );
}

# elimino els pop3 del rode i del moi des del GRIB i des de les IPs de sempre
for ( $i=0;$i<=$#log;$i++) {
   print STDERR "\rPOP3: $i/$#log          ";
   if ( $log[$i] =~ /gnu-pop3d\[(\d+)\]: connect from (.+)$/ ) {
      $PID=$1;
      $maquina=$2;
      if ( $maquina =~ /(193\.146\.190\.\d+|193\.147\.241\.\d+|45.red-213-96-48.pooles.rima-tde.net|fpuigvert.cesca.es)$/ ) {
         for ( $j=$i;$j<=$#log;$j++ ) {
            if ( $log[$j] =~ /gnu-pop3d\[$PID\]: / ) {
               $comanda=$';
               splice(@log,$j,1);
               $j--;
               if ( $comanda =~ /Session ended for user:/ ) {
                  last;
               }
            }
         }
         $i--;
      }
   }
}
print STDERR "\n";

# elimino els sendmail des de jupiter i des de basquet
for ( $i=0;$i<=$#log;$i++) {
   print STDERR "\rSENDMAIL: $i/$#log          ";
   if ( $log[$i] =~ /sendmail\[\d+\]: connect from (jupiter|basquet)\.imim\.es$/ ) {
      splice(@log,$i,1);
      $i--;
   }
}
print STDERR "\n";

# elimino els ssh des d'IP fixes fiables: qualsevol IP GRIB, ADSL rguigo,
# ADSL jabril, ADSL mburset
for ( $i=0;$i<=$#log;$i++) {
   print STDERR "\rSSHD: $i/$#log          ";
   if ( $log[$i] =~ /sshd\[(\d+)\]: PAM _pam_init_handlers:/ ) {
      $inicial=$i-5; # -5 perque pot haver entrades previes amb el mateix PID (l'exploit del "Bye Bye", etc.)
      $PID=$1;
      for ( $j=$i;$j<=$#log;$j++ ) {
         if ( $log[$j] =~ /sshd\[$PID\]: (Accepted|Failed) / ) {
            $log[$j] =~ / from (\d+\.\d+\.\d+\.\d+) port /;
            $maquina=$1;
         } elsif ( $log[$j] =~ /sshd[^\[]*\[$PID\]: (session closed|Connection closed|Timeout|Received disconnect)/ ) {
            last;
         }
      }
      $final=$j+20; # si no apareix res mes amb aquest PID 20 linies despres, asumeixo que ja no apareixera
      if ( $maquina =~ /(193\.146\.190\.\d+|193\.147\.241\.\d+|213\.96\.48\.45|193\.62\.201\.130|80\.224\.32\.5)/ ) {
         for ( $j=$inicial;$j<=$final;$j++) {
            if ( $log[$j] =~ /sshd[^\[]*\[$PID\]:/ ) {
               splice(@log,$j,1);
               $j--;
               $i--;
            }
         }
      }
   }
}
print STDERR "\n";

# elimino les entrades de l'exploit tocapilotes, pero nomes les que esta clar
# que no representen cap problema que s'hagi de revisar mes a fons.
#
# si l'usuari no existeix:
#
#    sshd[...]: input_userauth_request: illegal user ...
#    sshd[...]: PAM _pam_init_handlers: no default config /etc/pam.d/other
#    sshd[...]: Failed password for illegal user ... from ... port .... ssh...
#    sshd[...]: Received disconnect from ...: 11: Bye Bye
#
# i si existeix:
#
#    sshd[...]: PAM _pam_init_handlers: no default config /etc/pam.d/other
#    sshd(pam_unix)[...]: authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=...  user=...
#    sshd[...]: Failed password for ... from ... port ... ssh...
#    sshd[...]: Received disconnect from ...: 11: Bye Bye


# mostro el que queda
$cerca[0]="sendmail";
$cerca[1]="gnu-pop3d";
$cerca[2]="(telnetd|login)";
$cerca[3]="sshd";
foreach $j (@cerca) {
   print "="x70;
   print "\n$j\n";
   print "-"x(length($j)) . "\n";
   print grep( /:apolo $j/ , @log );
   @log=grep( ! /:apolo $j/ , @log );
}
print "="x70;
print "\nresta\n-----\n";
print "@log";

# fem el moviment de fitxers de log. INTENTA CONTROLAR QUE EL DE /root NO
# CREIXI MASSA!!!
system("cat oSYSLOG >> /root/SYSLOG");
system("mv SYSLOG oSYSLOG");
system("killall -HUP syslogd");
