#!/bin/bash

# la idea es empaquetar els fitxers d'un mes donat en un sol tar

# especifica el mes amb una expressio regular, per fer-ho mes facil

# primer parametre: nom del tgz que es crea i del directori on ficarem els
# fitxers abans d'empaquetar
# segon parametre: expressio regular del mes buscat

# dono per fet que soc al directori WebFiles
# si els fitxers estan comprimits, els descomprimeixo abans de fer el tgz

# poso al fitxer data del dia 1 del mes seguent a l'indicat com a parametre 1

# un exemple: (PATH)/compacta_geneid 2003-09 " Sep .. ..:.. " ==> 2003-09.tgz

if [ $# != 2 ]
then
   echo faltan parametres
   exit
fi

for direc in *
do
   echo -n $direc:
   if [ -d $direc ]
   then
      cd $direc
      mkdir $1
      ls -lt | egrep "$2" | awk '{ print $9 }' | grep -v "^20..-..\.tgz$" \
      | while read nom
      do
         mv $nom $1 # ho fem 1 a 1 perque si hi ha mes de 2048, peta
      done
      gunzip -f $1/*gz 2>/dev/null
      tar -czf $1.tgz $1
      cd ..
      echo " " `ls -l $direc/$1.tgz`
      echo "   direc:" `ls -l $direc/$1 | wc -l`
      echo "   tgz  :" `tar -vtzf $direc/$1.tgz | wc -l`
   else
      echo " no es un directori"
   fi
done
