#!/bin/bash

# si no tenim una versio prou nova de LILO (i la del RH73 no ho es), l'hem
# d'instal.lar manualment a tots els discos per poder botar des de qualsevol
# d'ells.
#
# aquest script canvia la linia "boot=/dev/sda" de /etc/lilo.conf per
# cadascun dels discos botables del RAID, i llavors executa /sbin/lilo
#
# la idea es poder modificar el /etc/lilo.conf de manera generica, i despres
# amb aixo instal.lar el LILO a tot arreu. /etc/lilo.conf te "boot=/dev/sda"
# per assegurar-nos que una execucio "erronea" del /sbin/lilo no ens deixa
# un sistema no botable

echo NO CAL FER AIXO PERQUE POSAR boot=/dev/md0 ES MILLOR!!!
exit

touch lilo.log.tmp1

for i in sda sdb
do
   echo Instal.lant LILO a /dev/$i...
   echo
   echo 'boot=/dev/'$i >lilo.conf.tmp
   # eliminem la linia "boot=..." original
   grep -v "boot=/dev/" /etc/lilo.conf >>lilo.conf.tmp
   /sbin/lilo -v -C lilo.conf.tmp >lilo.log.tmp2 2>&1
   paste lilo.log.tmp[12]
   echo
done

rm lilo.conf.tmp lilo.log.tmp[12]
