#!/bin/bash

# -b: linka des del bin corresconent al directori actual
# -l: linka des del lib corresponent al directori actual
# -m: linka des del man corresponent al directori actual
# el directori es /usr/local o /usr/local/molbio segons el cas

# amb -f linka per collons; contrariament, si existeix quelcom amb el
# mateix nom (link o fitxer) avisa pero no fa res. si linka al mateix
# punt, ni avisa ni res (perque segones execucions no han d'avisar dels
# links creats per la primera)

# amb -t nomes informa de que fara, independentment de si fem -f o no.
# es per si vull fer una primera revisio


# crea el link... si pot
crealink() {
   linkexec="$2"
   linkorig="$1/$2"
   linkdest="$diract/$2"
   if [ -d "$linkorig" ]
   then
      echo "   Ignorat: directori $linkexec"
      return
   fi
   while [ -L "$linkorig" ] # si el desti es un link, millor linkem al desti final
   do
      desti=`ls -l "$linkorig" | awk '{ print $11 }'`
      if [ /${desti#?} = $desti ]
      then # link absolut
         linkorig=$desti
      else # link relatiu
         linkorig="`dirname $linkorig`/$desti"
      fi
      linkorig=`cd \`dirname $linkorig\` ; pwd`/`basename $linkorig` # per si hi queda <direcs>/../<direcs>
      linkorig=..${linkorig#$dirinst} # aixo es valid perque abans ja hem donat per fet que
                                      # l'estructura era /usr/local/{[molbio/]Install
   done
   if [ $force = 0 ]
   then
      if [ -L "$linkexec" ] # existeix i es un link
      then
         desti=`ls -l "$linkexec" | awk '{ print $11 }'`
         if [ "$desti" != "$linkorig" ] # si apunta a un altre lloc, avisem
         then
            echo "   Ignorat: link $linkexec -> $desti"
         fi
         return
      elif [ -s "$linkexec" ] # existeix i es un fitxer
      then
         echo "   Ignorat: fitxer $linkexec"
         return
      fi
   fi
   echo "   $linkdest -> $linkorig"
   if [ $test != 1 ]
   then
      ln -sf "$linkorig" "$linkdest"
   fi
}


# main
force=0
test=0
dest=""
while [ $# != 0 ]
do
   case $1 in
      -b ) if [ "$dest" = "" ]
           then
              dest=bin
           else
              echo "$1 ignorat: instal.lacio definida a $dest"
           fi
           ;;
      -l ) if [ "$dest" = "" ]
           then
              dest=lib
           else
              echo "$1 ignorat: instal.lacio definida a $dest"
           fi
           ;;
      -m ) if [ "$dest" = "" ]
           then
              dest=man
           else
              echo "$1 ignorat: instal.lacio definida a $dest"
           fi
           ;;
      -f ) force=1
           ;;
      -t ) test=1
           ;;
      -* ) echo parametre $1 no reconegut
           exit
           ;;
      *  ) break
           ;;
   esac
   shift
done
if [ "$dest" = "" ]
then
   echo "Tipus d'instal.lacio no definida: -e, -l o -m!!!"
   exit
fi

diract=`pwd`
dirinst=${diract%/Install/*}
dirlink=..${diract#$dirinst}
if [ $diract = $dirinst ]
then
   echo "`pwd`: No som a un subdirectori de /usr/local[/molbio]/Install"
   exit
fi
if [ $dirinst != "/usr/local" -a $dirinst != "/usr/local/molbio" ]
then
   echo "`pwd`: No som a /usr/local[/molbio]"
   exit
fi

cd $dirinst/$dest
if [ $dest != man ]
then
   if [ $# = 0 ]
   then
      echo "Fitxers a linkar no especificats!!!"
      exit
   fi
   diract=`pwd`
   while [ $# != 0 ]
   do
      crealink "$dirlink" "$1"
      shift
   done
else
   if [ $# = 0 ]
   then
      echo "Directoris amb les \"manpages\" a linkar no especificats!!!"
      exit
   fi
   while [ $# != 0 ]
   do
      if [ -d $dirlink/$1 ]
      then
         diract=`pwd`
         for manpage in $dirlink/$1/*
         do
            crealink "../$dirlink" "$1/`basename $manpage`"
         done
      else
         echo "$1 no existeix"
      fi
      shift
   done
fi

if [ $test = 1 ]
then
   echo "Execucio de prova: cap link creat"
fi
