#!/usr/bin/perl

# la idea es fer el "download" amb wget i aprofitar els .listing per
# esborrar allo que ja no es troba al servidor
#
# en acabar, eliminem els .listing perque ja no serveixen per res
#
# la rutina funciona de manera recursiva des del directori actual
#
# -n provoca que els fitxers s'esborrin (contrariament nomes informa)
# -t canvia manualment el "timestamp" dels fitxers (per si ha fallat)
# COMPTE: ESTA FET TAN GUARRAMENT QUE -n HA DE SER EL PRIMER FLAG I -s EL
# SEGON!!!

use File::Path;

sub direc {
   my $RUTA="$_[0]$_[1]";
   my $nom;
   my @listing;
   my %hores;
   chdir("$_[1]");
   opendir(DIR,".");
   my @dirlist=sort(grep(!/^(\.|\.\.|\.listing)$/,readdir(DIR)));
   closedir(DIR);
   if ( -e ".listing" ) {
      # no sempre hi ha .listing, pero si hi es fem neteja
      open(FIT,".listing");
      while (<FIT>) {
         next if ( /(^total| ^\.\.?$)/ );
         chomp;
         @tmp=split(/\s+/og,$_);
         push(@listing,$tmp[8]);
         if ( $timestamp ) {
            $mes=$mesos{$tmp[5]};
            $dia=substr("0$tmp[6]",length($tmp[6])-1,2);
            $extra=$tmp[7];
            if ( $extra =~ /:/ ) {
               # es prou nou i ve en format mes dia hora
               $extra =~ s/://;
               $mesactual=$mesos{(split(/\s+/og,`date`))[1]};
               $any=(split(/\s+/og,`date`))[5];
               if ( $mesactual < $mes ) {
                  $any--;
               }
               $hora="$any$mes$dia$extra.00";
            } else {
               # es antic i ve en format mes dia any
               $hora="$extra$mes${dia}1200.00";
            }
            $hores{"$tmp[8]"}=$hora;
         }
      }
      close(FIT);
      for (my $index=0;$index<=$#dirlist;$index++) {
         print STDERR "\b"x20;
         print STDERR "$index/$#dirlist";
         $nom=$dirlist[$index];
         if ( $nom =~ /[^A-Za-z0-9_\-\.]/ ) {
            print STDERR "ATENCIO: \"$nom\" a \"$RUTA\"\n";
            $conflictius++;
            if ( grep(/^$nom$/,@listing) ) {
               print STDERR "   (no esborrar...)\n";
            } else {
               print STDERR "   (esborrar...)\n";
            }
            next;
         }
         my $trobat=0;
         for (my $index2=0;$index2<=$#listing;$index2++) {
            if ( $nom eq $listing[$index2] ) {
               if ( -d "$nom" ) {
                  print STDERR "\n";
                  &direc("$RUTA/",$nom);
               }
               splice(@listing,$index2,1);
               $trobat=1;
               # com que de vegades no posa l'hora que correspon,
               # la poso jo manualment si s'ha especificat que s'ha
               # de fer: flag -t. he de pulir aixo.
               if ( $timestamp ) {
                  system("touch -t $hores{$nom} $nom");
               }
               last;
            }
         }
         if ( $trobat == 0 ) {
            $esborrats++;
            if ( $neteja ) {
               print STDERR " - Eliminant $RUTA/$nom\n";
               rmtree("$nom");
            } else {
               print STDERR " - Trobat $RUTA/$nom\n";
            }
         }
      }
      print STDERR "\n";
      unlink(".listing");
   } else {
      # ens limitem a entrar en els subdirectoris
      foreach $nom (@dirlist) {
         if ( -d "$nom" ) {
            &direc("$RUTA/",$nom);
         }
      }
   }
   chdir("..");
}

$mesos{"Jan"}="01";
$mesos{"Feb"}="02";
$mesos{"Mar"}="03";
$mesos{"Apr"}="04";
$mesos{"May"}="05";
$mesos{"Jun"}="06";
$mesos{"Jul"}="07";
$mesos{"Aug"}="08";
$mesos{"Sep"}="09";
$mesos{"Oct"}="10";
$mesos{"Nov"}="11";
$mesos{"Dec"}="12";

$esborrats=0;
$conflictius=0;
$neteja=( $ARGV[1] eq "-n" );
$timestamp=( $ARGV[2] eq "-t" );

&direc("",$ARGV[0]);

print "Esborrats: $esborrats\n";
print "Dubtosos : $conflictius\n";
