#!/bin/bash

##########
# revisa la sortida d'un wget i indica si s'ha baixat res o no
# i si ha baixat be
# aquesta sortida sempre es troba al /tmp/MirrorRefSeq, pero
# s'acaba afegint al "log" generic
##########
filtre() {
   echo
   echo ----------
   echo
   echo $local: $AVIS
   echo
   grep ^Downloaded $OUT
   echo
   date +"%d %b %Y - %H:%M"
   /home/ug/ogonzalez/scripts/comprimits <$OUT
   echo
   date +"%d %b %Y - %H:%M"
   if [ "$1" != "NO_RM" ]
   then
      /home/ug/ogonzalez/scripts/mirror $local -n
   fi

   cat $OUT >>$LOG
   rm $OUT

} >>$MAIL

#######################################################
#######################################################

# busquem uns noms unics: si s'arrenca mes d'un mirror alhora, ens hem
# d'assegurar que un no matxaca els fitxers de l'altre. tot i que el segon
# mirror no fara res, necessita crear alguns fitxers temporals.
# el que fem es emprar el PID del proces

DIREC=/tmp/MirrorRefSeq
OUT=$DIREC.out
MAIL=$DIREC.mail
LOG=$DIREC.log
PID=$DIREC.pid
LOGDIR=/home/ug/ogonzalez/scripts/_LOGS

echo Mirror arrencat: `date +"%d %b %Y - %H:%M"` >$MAIL

if [ -e $PID ]
then

   PIDVELL=`cat $PID`
   if [ `ps -e | grep -c "^ *$PIDVELL"` != 0 ]
   then
      # JA HI HA UN MIRROR EN MARXA
      echo >>$MAIL
      echo JA HI HA UN MIRROR EN MARXA!!! >>$MAIL
      echo >>$MAIL
   else
      # L'EXECUCIO ANTERIOR NO VA ACABAR NETAMENT
      # DAVANT DEL DUBTE, TAMPOC CONTINUO EL MIRROR
      echo >>$MAIL
      echo Fitxer $PID detectat >>$MAIL
      echo >>$MAIL
   fi
   echo EXECUCIO CANCEL.LADA >>$MAIL | tee $LOG

else

   echo $$ >$PID

   rm -rf $LOG >/dev/null 2>&1

   ##########
   # RefSeq
   ##########

      URL=ftp://ftp.ncbi.nih.gov/refseq
      local=/seq/databases/refseq

      excdirecs=/refseq/cumulative,/refseq/daily

      cd $local
      wget -m -nH --cut-dirs=1 --passive-ftp --progres=dot:mega -X $excdirecs $URL 2>&1 | tee $OUT

      AVIS=""

      filtre

########################################################
# 24-ago-2005: aixo ja no es fa des d'aqui!!!
########################################################
#   ##########
#   # GoldenPath - ensGene, ensPep, refGene...
#   ##########
#
#      URL=http://hgdownload.cse.ucsc.edu/goldenPath
#      rm $OUT
#      AVIS=""
#
#      rm /tmp/gp >/dev/null 2>&1
#      for organisme in H.sapiens M.musculus R.norvegicus
#      do
#         for local in `ls -1d /seq/compressed_genomes/$organisme/golden_path* | tail -3`
#         do
#            cd $local/database
#            nom=`basename $local`
#            remot=`grep $nom$ /home/ug/ogonzalez/scripts/MirrorGP.dat | awk '{ print $1 }'`
#            for fitxer in acembly all_est ECgene ensEstGene ensGene ensLink ensMrna ensPep exoniphy geneid genscan knownGene mgcGenes miRNA pseudoGeneLink refGene refLink refMrna refPep rnaGene sgpGene snpMap snpNih softberryGene superfamily tableDescriptions transRegCode transRegCodeCondition transRegCodeMotif transRegCodeProbe twinscan vegaGene vegaPseudoGene
#            do
#               echo "$URL/$remot/database/$fitxer.sql" >>/tmp/gp
#               echo "$URL/$remot/database/$fitxer.txt.gz" >>/tmp/gp
#            done
#            wget -m -nH -nd --passive-ftp --progres=dot:mega -i /tmp/gp 2>&1 | tee $OUT
#            #wget -N -nH -nd --passive-ftp -i /tmp/gp 2>&1 | tee $OUT
#            rm /tmp/gp
#            filtre NO_RM
#         done
#      done

fi

#######################################################

echo >>$MAIL
echo ---------- >>$MAIL
echo >>$MAIL

data=`date +"%d %b %Y - %H:%M"`
echo Mirror acabat: $data >>$MAIL

mail -s"MirrorRefSeq $data" ogonzalez@imim.es <$MAIL
rm $MAIL
NOM=mrs-`date +%Y%m%d-%H%M`
mv $LOG $LOGDIR/$NOM
cd $LOGDIR
chown ogonzalez:users $NOM
gzip $NOM

ls -t1 mrs* | tee $OUT | head -10 >$LOG
rm -f `diff $OUT $LOG | grep '^<' | cut -c3-` $OUT $LOG
