#!/bin/bash

##########
# revisa la sortida d'un wget i indica si s'ha baixat res o no
# i si ha baixat be
# aquesta sortida sempre es troba al /tmp/MirrorDatabases, pero
# s'acaba afegint al "log" generic
##########
filtre() {
   echo
   echo ----------
   echo
   echo $local: $AVIS
   echo
   grep ^Downloaded $OUT
   echo
   echo -n 'Revisant comprimits - '
   date +"%d %b %Y - %H:%M"
   /home/ug/ogonzalez/scripts/comprimits <$OUT
   echo
   echo -n 'Revisant eliminats - '
   date +"%d %b %Y - %H:%M"
   if [ "$1" != -norm ]
   then
      /home/ug/ogonzalez/scripts/mirror $local -n
   fi

   cat $OUT >>$LOG
   rm $OUT

} >>$MAIL

#######################################################
#######################################################

FTPSITE=ftp://ftp.es.embnet.org

# busquem uns noms unics: si s'arrenca mes d'un mirror alhora, ens hem
# d'assegurar que un no matxaca els fitxers de l'altre. tot i que el segon
# mirror no fara res, necessita crear alguns fitxers temporals.
# el que fem es emprar el PID del proces

OUT=/tmp/MirrorDatabases$$
MAIL=/tmp/MirrorDatabasesMail$$
LOG=/tmp/MirrorDatabasesLog$$
LOGDIR=/home/ug/ogonzalez/scripts/_LOGS
PID=/tmp/MirrorDatabasesPID

echo Mirror arrencat: `date +"%d %b %Y - %H:%M"` >$MAIL

if [ -e $PID ]
then
   PIDVELL=`cat $PID`
   if [ `ps -e | grep -c "^ *$PIDVELL"` != 0 ]
   then
      # JA HI HA UN MIRROR EN MARXA
      echo >>$MAIL
      echo JA HI HA UN MIRROR EN MARXA!!! >>$MAIL
      echo >>$MAIL
   else
      # L'EXECUCIO ANTERIOR NO VA ACABAR NETAMENT
      # DAVANT DEL DUBTE, TAMPOC CONTINUO EL MIRROR
      echo >>$MAIL
      echo Fitxer $PID detectat >>$MAIL
      echo >>$MAIL
   fi
   echo EXECUCIO CANCEL.LADA >>$MAIL | tee $LOG

else

   echo $$ >$PID

   rm -rf $LOG >/dev/null 2>&1

   ##########
   # EMBL - release
   ##########

      URL=$FTPSITE/databases/embl/release
      local=/seq/databases/embl/release

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      versio=`ls -1 Release_* | tail -1`
      # COMPTE: AIXO DEPEN DE $local
      cd ../..
      if [ ! -L embl-$versio ]
      then
         rm embl-Release_[0-9][0-9]
         ln -sf embl/release embl-$versio
         AVIS="LA RELEASE HA CANVIAT"
      fi

      filtre

   ##########
   # EMBL - new
   ##########

      URL=$FTPSITE/databases/embl/new
      local=/seq/databases/embl/new
      excfiles=newentries.ndx,*cumulative.dat.gz*,.NEW,.week.gz,r[0-9][0-9]u*.dat.gz
      excdirecs=/pub/databases/embl/new/list

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega -R $excfiles -X $excdirecs $URL 2>&1 | tee $OUT

      AVIS=""

      filtre

   ##########
   # SWISS-PROT - release_compressed
   ##########

      URL=$FTPSITE/databases/swiss-prot/release_compressed
      local=/seq/databases/swiss-prot/release_compressed

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # SWISS-PROT - updates_compressed
   ##########

      URL=$FTPSITE/databases/swiss-prot/updates_compressed
      local=/seq/databases/swiss-prot/updates_compressed

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # TREMBL - release_compressed
   ##########

      URL=$FTPSITE/databases/trembl/release_compressed
      local=/seq/databases/trembl/release_compressed

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # SP_TR_NRDB
   ##########

      URL=$FTPSITE/databases/sp_tr_nrdb
      local=/seq/databases/sp_tr_nrdb

      cd $local
      wget -m -nH --cut-dirs=2 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # PIR - release
   ##########

      URL=$FTPSITE/databases/pir/release
      local=/seq/databases/pir/release

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # PIR - updates
   ##########

      URL=$FTPSITE/databases/pir/updates
      local=/seq/databases/pir/updates

      cd $local
      wget -m -nH --cut-dirs=3 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # PDB_SEQ
   ##########

      URL=$FTPSITE/databases/pdb_seq
      local=/seq/databases/pdb_seq

      cd $local
      wget -m -nH --cut-dirs=2 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # PDB
   ##########

      # no volem recrear l'estructura del servidor, sino tenir totes les
      # molecules al mateix directori. per aixo fem -nd
      # PROBLEMA: ELS .listing NO SON COMPLETS, AIXI QUE NO PODEM BASAR-NOS
      # EN ELLS PER ESBORRAR FITXERS DESAPAREGUTS AL SERVIDOR. DESACTIVO
      # AQUESTA FUNCIONALITAT AMB EL -norm A filtre

      URL=$FTPSITE/databases/pdb/structures/divided/pdb
      local=/seq/databases/pdb

      cd $local
      wget -m -nH -nd --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre -norm

   ##########
   # PFAM
   ##########

      URL=$FTPSITE/databases/Pfam
      local=/seq/databases/pfam

      cd $local
      wget -m -nH --cut-dirs=2 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ##########
   # HSSP
   ##########

      URL=$FTPSITE/databases/hssp
      local=/seq/databases/hssp

      cd $local
      wget -m -nH --cut-dirs=2 --progres=dot:mega $URL 2>&1 | tee $OUT

      filtre

   ###############
   # nomes quan acaben tots els mirrors puc esborrar $PID
   rm $PID

fi

#######################################################

echo >>$MAIL
echo ---------- >>$MAIL
echo >>$MAIL

data=`date +"%d %b %Y - %H:%M"`
echo Mirror acabat: $data >>$MAIL

mail -s"MirrorDatabases $data" ogonzalez@imim.es <$MAIL
rm $MAIL
NOM=mdb-`date +%Y%m%d-%H%M`
mv $LOG $LOGDIR/$NOM
cd $LOGDIR
chown ogonzalez:users $NOM
gzip $NOM

ls -t1 mdb* | tee $OUT | head -10 >$LOG
rm -f `diff $OUT $LOG | grep '^<' | cut -c3-` $OUT $LOG
