#!/bin/bash

#########################################################################
#
# ATENCIO:
#
# PER BAIXAR UN SOL ORGANISME, EXECUTA MirrorGoldenPath.1!!!!
#
#########################################################################


#if [ `whoami` != bdadmin ]
#then
#   echo Has de ser bdadmin
#   exit
#fi

URL[0]=http://genome-archive.cse.ucsc.edu/goldenPath
URL[1]=http://hgdownload.cse.ucsc.edu/goldenPath
genomes=/seq/compressed_genomes
llista=/home/ug/ogonzalez/scripts/MirrorGoldenPath.lst

cat $llista | cut -d\# -f1 | while read linia
do
   organisme=${linia%:}
   if [ "$organisme:" = "$linia" ]
   then
echo $organisme---
      while read col1 col2
      do
         if [ "$col1" = "" ]
         then
            break
         fi
         direc=${col1#??}
         servidor=${col1%?$direc}
         dirremot=${URL[$servidor]}/$direc
         dirlocal=$genomes/$col2
# AQUEST IF S'HAURIA DE FER A MIRRORGOLDENPATH.1!!!!
         if wget --spider $dirremot &> /dev/null
         then
echo ${URL[$servidor]}/$direc - $genomes/$local
#         cd $dirlocal
#         /home/ug/ogonzalez/scripts/MirrorGoldenPath.1 $dirremot
#         echo "Mirrored from $URL/$remot" > README.txt
#         echo -n "Last mirrored on " >> README.txt
#         date >> README.txt
         else
            echo "ERROR DE CONNEXIO, O JO QUE SE"
         fi
      done
echo
   fi
done

