#!/bin/ksh

# Sincronitza /aplicacions/genomics/linux a darwin amb /usr/local a monstre1
#
# Es fa una copia incremental amb "cp -afuv" i s'esborra el que pugui
# sobrar amb l'script "direcmirror"
#
# Abans de res munta el disc de darwin a monstre1, i en acabar el desmunta
#
# PER ARA NO ESBORRA RES!!! ES LIMITA A COPIAR.***********************


if [ -d /__M1__ ]
then
   echo __M1__ JA EXISTEIX
   exit
fi
mkdir /__M1__

mount -t nfs darwin:/aplicacions/genomics/linux /__M1__
if [ ! -d /__M1__/molbio ] # manera farsa de mirar si esta ben muntat
then
   echo __M1__ NO ESTA BE
   exit
fi

cp -afuv /usr/local/* /__M1__

umount /__M1__
rmdir /__M1__
