#!/bin/bash

##########
# revisa la sortida d'un wget i indica si s'ha baixat res o no
# i si ha baixat be
# aquesta sortida sempre es troba al /tmp/MirrorDatabases, pero
# s'acaba afegint al "log" generic
##########
filtre() {
   echo
   echo ----------
   echo
   echo $local:
   echo
   grep ^Downloaded $OUT
   echo
   date +"%d %b %Y - %H:%M"
   /home/ug/ogonzalez/scripts/comprimits <$OUT
   echo
   date +"%d %b %Y - %H:%M"
   /home/ug/ogonzalez/scripts/mirror $local -n

   cat $OUT >>$LOG
   rm $OUT

} >>$MAIL

#######################################################
#######################################################

FTPSITE=ftp://ftp.ebi.ac.uk

OUT=/tmp/MIrrorDatabases
MAIL=/tmp/MIrrorDatabasesMail
LOG=/tmp/MIrrorDatabasesLog
LOGDIR=/home/ug/ogonzalez/scripts/MirrorDatabases.log
rm -rf $OUT $MAIL $LOG >/dev/null 2>&1

echo Mirror arrencat: `date +"%d %b %Y - %H:%M"` >$MAIL
echo >>$MAIL
echo NOMES EMBL/RELEASE I EMBL/NEW DES DE EBI >>$MAIL

##########
# EMBL - release
##########

   URL=$FTPSITE/pub/databases/embl
   local=/seq/databases/embl/release

   cd $local
   wget -m -nH --cut-dirs=4 $URL/release 2>&1 | tee $OUT

   if [ -L $local/release ]
   then
      versio=`ls -l $local/release | awk '{ print $11 }'`
      wget -m -nH --cut-dirs=4 $URL/$versio 2>&1 | tee $OUT
   fi

   versio=`ls Release_*`
   if [ ! -L /seq/databases/embl-$versio ]
   then
      rm /seq/databases/embl-Release_[0-9][0-9]
      ln -sf embl /seq/databases/embl-$versio
      echo LA RELEASE HA CANVIAT >>$MAIL
   fi

   filtre

##########
# EMBL - new
##########

   URL=$FTPSITE/pub/databases/embl/new
   local=/seq/databases/embl/new
   excfiles=newentries.ndx,*cumulative.dat.gz*,.NEW,.week.gz,r[0-9][0-9]u*.dat.gz
   excdirecs=/pub/databases/embl/new/list

   cd $local
   wget -m -nH --cut-dirs=4 -R $excfiles -X $excdirecs $URL 2>&1 | tee $OUT

   filtre

#######################################################

echo
echo ----------
echo

data=`date +"%d %b %Y - %H:%M"`
echo Mirror acabat: $data >>$MAIL

mail -s"MirrorDatabases $data" ogonzalez@imim.es <$MAIL
rm $MAIL
data=`date +%Y%m%d-%H%M`
mv $LOG $LOGDIR/$data
chown oscar:users $LOGDIR/$data

