#!/bin/bash

##########
download() {
   AVIS=""
   cd $local
   rm -f index.html 2>/dev/null
   if [ -e index.html ]
   then
      AVIS="IMPOSSIBLE ESBORRAR INDEX ANTERIOR"
      return
   fi
   URL=$FTPSITE1/$URLPATH
   wget --passive-ftp $URL/
   if [ ! -e index.html ]
   then
      URL=$FTPSITE2/$URLPATH
      wget $URL/
      if [ ! -e index.html ]
      then
         AVIS="IMPOSSIBLE CONNECTAR... APARENTMENT..."
         return
      fi
   fi
   rm index.html
   cutdirs=`echo $URL | awk -F/ '{ print "--cut-dirs="NF-3 }'`
   flags="-m -nH --passive-ftp --progres=dot:mega"
   wget $flags $cutdirs $excfiles $excdirecs $URL/ 2>&1 | tee $OUT
}

##########
# revisa la sortida d'un wget i indica si s'ha baixat res o no
# i si ha baixat be
# aquesta sortida sempre es troba al /tmp/MirrorDatabases, pero
# s'acaba afegint al "log" generic
##########
filtre() {
   echo
   echo ----------
   echo
   echo $local: $AVIS
   echo
   grep ^Downloaded $OUT
   echo
   echo -n 'Revisant comprimits - '
   date +"%d %b %Y - %H:%M"
   /home/ug/ogonzalez/scripts/comprimits <$OUT
   echo
   echo -n 'Revisant eliminats - '
   date +"%d %b %Y - %H:%M"
   if [ "$1" != -norm ]
   then
      /home/ug/ogonzalez/scripts/mirror $local -n
   fi

   cat $OUT >>$LOG
   rm $OUT

} >>$MAIL

#######################################################
#######################################################

# busquem uns noms unics: si s'arrenca mes d'un mirror alhora, ens hem
# d'assegurar que un no matxaca els fitxers de l'altre. tot i que el segon
# mirror no fara res, necessita crear alguns fitxers temporals.
# el que fem es emprar el PID del proces

DIREC=/tmp/MirrorDatabases
OUT=$DIREC.out
MAIL=$DIREC.mail
LOG=$DIREC.log
PID=$DIREC.pid
LOGDIR=/home/ug/ogonzalez/scripts/_LOGS

echo Mirror arrencat: `date +"%d %b %Y - %H:%M"` >$MAIL

if [ -e $PID ]
then

   PIDVELL=`cat $PID`
   if [ `ps -e | grep -c "^ *$PIDVELL"` != 0 ]
   then
      # JA HI HA UN MIRROR EN MARXA
      echo >>$MAIL
      echo JA HI HA UN MIRROR EN MARXA!!! >>$MAIL
      echo >>$MAIL
   else
      # L'EXECUCIO ANTERIOR NO VA ACABAR NETAMENT
      # DAVANT DEL DUBTE, TAMPOC CONTINUO EL MIRROR
      echo >>$MAIL
      echo Fitxer $PID detectat >>$MAIL
      echo >>$MAIL
   fi
   echo EXECUCIO CANCEL.LADA >>$MAIL | tee $LOG

else

   echo $$ >$PID

   rm -rf $LOG >/dev/null 2>&1

   FTPSITE1=ftp://ftp.es.embnet.org/pub
   FTPSITE2=ftp://ftp.ebi.ac.uk/pub

   ##########
   # EMBL - release
   ##########

      URLPATH=databases/embl/release
      local=/seq/databases/embl/release
      excfiles=""
      excdirecs=""

      download

      versio=`ls -1 Release_* | tail -1`
      # COMPTE: AIXO DEPEN DE $local
      cd ../..
      if [ ! -L embl-$versio ]
      then
         rm embl-Release_[0-9][0-9] 2>/dev/null
         ln -sf embl/release embl-$versio
         AVIS="LA RELEASE HA CANVIAT"
      fi

      filtre

   ##########
   # EMBL - new
   ##########

      URLPATH=databases/embl/new
      local=/seq/databases/embl/new
      excfiles="-R newentries.ndx,*cumulative.dat.gz*,.NEW,.week.gz,r[0-9][0-9]u*.dat.gz"
      excdirecs="-X /pub/databases/embl/new/list"

      download
      filtre

   ##########
   # SWISS-PROT - release_compressed
   ##########

      # temporal mentre baixem directament de l'EBI
      URLPATH=databases/uniprot/current_release/knowledgebase/complete
      #URL=$FTPSITE/databases/swiss-prot/release_compressed
      excfiles=""
      excdirecs=""
      local=/seq/databases/swiss-prot/release_compressed

      download
      filtre

   ##########
   # SWISS-PROT - updates_compressed
   ##########

      URLPATH=/databases/swiss-prot/updates_compressed
      excfiles=""
      excdirecs=""
      local=/seq/databases/swiss-prot/updates_compressed

      download
      filtre

   ##########
   # TREMBL - release_compressed
   ##########

#      URL=$FTPSITE/databases/trembl/release_compressed
#      local=/seq/databases/trembl/release_compressed
#
#      cd $local
#      wget -m -nH --cut-dirs=3 --passive-ftp --progres=dot:mega $URL 2>&1 | tee $OUT

#      filtre

   ##########
   # SP_TR_NRDB
   ##########

#      URL=$FTPSITE/databases/sp_tr_nrdb
#      local=/seq/databases/sp_tr_nrdb
#
#      cd $local
#      wget -m -nH --cut-dirs=2 --passive-ftp --progres=dot:mega $URL 2>&1 | tee $OUT
#
#      filtre

   ##########
   # PIR
   ##########

      URLPATH=databases/pir
      excfiles=""
      excdirecs=""
      local=/seq/databases/pir

      download
      filtre

   ##########
   # PDB_SEQ
   ##########

      URLPATH=databases/pdb_seq
      excfiles=""
      excdirecs=""
      local=/seq/databases/pdb_seq

      download
      filtre

   ##########
   # PDB
   ##########

#      # no volem recrear l'estructura del servidor, sino tenir totes les
#      # molecules al mateix directori. per aixo fem -nd
#      # PROBLEMA: ELS .listing NO SON COMPLETS, AIXI QUE NO PODEM BASAR-NOS
#      # EN ELLS PER ESBORRAR FITXERS DESAPAREGUTS AL SERVIDOR. DESACTIVO
#      # AQUESTA FUNCIONALITAT AMB EL -norm A filtre
#
#      URL=$FTPSITE/databases/pdb/structures/divided/pdb
#      local=/seq/databases/pdb
#
#      cd $local
#      wget -m -nH -nd --passive-ftp --progres=dot:mega $URL 2>&1 | tee $OUT
#
#      filtre -norm

   ##########
   # PFAM
   ##########

      URLPATH=databases/Pfam
      excfiles=""
      excdirecs=""
      local=/seq/databases/pfam

      download
      filtre

   ##########
   # HSSP
   ##########

      # embnet espanya no te aquesta bdd completa ==> canvi de URL
      FTPSITE1=ftp://ftp.ebi.ac.uk/pub
      URLPATH=databases/hssp
      excfiles=""
      excdirecs=""
      local=/seq/databases/hssp

      download
      filtre

   ##########
   # DSSP
   ##########

      # embnet espanya no te aquesta bdd completa ==> canvi de URL
      FTPSITE1=ftp://ftp.ebi.ac.uk/pub
      URLPATH=databases/dssp
      excfiles=""
      excdirecs=""
      local=/seq/databases/dssp

      download
      filtre

   ##########
   # ASD
   ##########

      # embnet espanya no te aquesta bdd ==> canvi de URL
      FTPSITE1=ftp://ftp.ebi.ac.uk/pub
      URLPATH=databases/ASD
      excfiles=""
      excdirecs=""
      local=/seq/databases/ASD

      download
      filtre

   ##########
   # GeneOntology - godatabase
   ##########

      # embnet espanya no te aquesta bdd ==> canvi de URL
      FTPSITE1=ftp://ftp.geneontology.org/pub
      FTPSITE2=$FTPSITE1
      URLPATH=godatabase/archive/latest
      excfiles=""
      excdirecs=""
      local=/seq/databases/GeneOntology/godatabase

      download

      versio=`ls -1 go_* | head -1 | cut -c4-9`
      # COMPTE: AIXO DEPEN DE $local
      cd ../..
      if [ ! -L GeneOntology-$versio ]
      then
         rm GeneOntology-200* 2>/dev/null
         ln -sf GeneOntology/godatabase GeneOntology-$versio
         AVIS="LA RELEASE HA CANVIAT"
      fi

      filtre

   ##########
   # GeneOntology - doc
   ##########

      URLPATH=go/doc
      excfiles=""
      excdirecs=""
      local=/seq/databases/GeneOntology/doc
   
      download
      filtre

   ##########
   # GeneOntology - gene-associations
   ##########

      URLPATH=go/gene-associations
      excfiles=""
      excdirecs=""
      local=/seq/databases/GeneOntology/gene-associations
   
      download
      filtre

   ##########
   # GeneOntology - ontology
   ##########

      URLPATH=go/ontology
      excfiles=""
      excdirecs=""
      local=/seq/databases/GeneOntology/ontology
   
      download
      filtre

   ###############
   # nomes quan acaben tots els mirrors puc esborrar $PID
   rm $PID

fi

#######################################################

echo >>$MAIL
echo ---------- >>$MAIL
echo >>$MAIL

data=`date +"%d %b %Y - %H:%M"`
echo Mirror acabat: $data >>$MAIL

mail -s"MirrorDatabases $data" ogonzalez@imim.es <$MAIL
rm $MAIL
NOM=mdb-`date +%Y%m%d-%H%M`
mv $LOG $LOGDIR/$NOM
cd $LOGDIR
chown ogonzalez:users $NOM
gzip $NOM

ls -t1 mdb* | tee $OUT | head -10 >$LOG
rm -f `diff $OUT $LOG | grep '^<' | cut -c3-` $OUT $LOG
