#!/bin/bash

rm zz.txt 2>/dev/null

typeset -i hores minuts segons

# llegim l'hora actual
hores=`date +%H`
minuts=`date +%M`

# i l'endarrerim 5 minuts (poso els segons a zero, pero no importa)
if (( minuts < 5 ))
then
   let minuts=minuts+60
   let hores=hores-1
fi
let minuts=minuts-5
h=$hores
if (( hores < 10 ))
then
   h=0$hores
fi
m=$minuts
if (( minuts < 10 ))
then
   m=0$minuts
fi
date -d $h$m

# imprimim l'hora cada 10 segons, a veure quant triga a estar be
# (he sincronitzat monstre1 abans de comencar, com a referencia)
while [ 1 = 1 ]
do
   sleep 10
   date >>zz.txt
   tail -1 zz.txt
done
