#!/bin/bash

# la idea es calcular quans fitxers i quants directoris hi ha a un
# directori. com md5sum, pero sense calcular els md5

tree -axF >/tmp/tree.out

total=`wc -l < /tmp/tree.out`
nodirec=`grep -v '/$' /tmp/tree.out | tee /tmp/tree.nodirec | wc -l`
nolink=`grep -v ' -> ' /tmp/tree.nodirec | tee /tmp/tree.nolink | wc -l`
fit=`wc -l < /tmp/tree.nolink`

let direc=total-nodirec
let link=nodirec-nolink

printf "Total     : %7i\n" $total
printf "Directoris: %7i\n" $direc
printf "Fitxers   : %7i\n" $fit
printf "Links     : %7i\n" $link

rm /tmp/tree.out /tmp/tree.nodirec /tmp/tree.nolink

