#!/bin/bash

# aixo genera fitxers en un directori ("z", en principi) per veure
# com creix la grandaria d'un directori en funcio del nombre de
# fitxers continguts

typeset -i num

rm z/*
size=`ls -ld z|awk '{ print $5 }'`

echo -n "$size: 0 -> "
num=1
num2=0

while :
do
   touch z/$num
   size2=`ls -ld z|awk '{ print $5 }'`
   if [ $size != $size2 ]
   then
      echo $num2
      size=$size2
      echo -n "$size: $num -> "
   fi
   num2=$num
   let num=num+1
done
