#!/bin/ksh

nom=pdb

for i in 0 1 2 3 4 5 6 7 8 9
#for i in  a b c d e f g h i j k l m n o p q r s t u v w x y z
do
   echo Fitxers $i:
   echo -n "   Calculant nombre de fitxers... "
   total1=`ls -1 $nom${i}* 2>/dev/null|wc -l`
   if [ $total1 != 0 ]
   then
      echo $total1
      echo -n "   Fent tar... "
      tar -cf _$nom${i}.tar $nom${i}*
      echo OK
      echo -n "   Revisant tar... "
      total2=`tar -vtf _$nom${i}.tar|wc -l`
      echo $total2
      if [ $total1 = $total2 ]
      then
         echo "   Coincideixen"
         echo -n "   Esborrant... "
         rm $nom${i}*
         echo OK
      else
         echo "-> ERROR A $i:" $total1 vs. $total2
         read a
      fi
   else
      echo 0
   fi
done
