#!/bin/bash

# mostra tot el que esta corrent a la cua de nautilus i les remotes
#
# nomes funciona des de maquines amb l'NQS instal.lat

echo

# una cua nomes mostra la capcelera de les columnes quan hi ha alguna
# cosa corrent. ningu no ens assegura que en una maquina concreta hi
# hagi res corrent (incloent-hi nautilus: pot no haver-hi res esperant)
# aixi que hem d'assegurar-nos que una o altra cua la mostra

# ens hem d'assegurar que el fitxer temporal es pot crear i que el d'un
# usuari no matxaca el d'un altre usuari si tots dos executen l'script
# alhora
temp=/tmp/qstat$$

# mostrem les cues on pot haver-hi jobs corrent
# acabem amb la cua main, aixi que nautilus ha de ser el darrer
for maquina in basileia drac mar tmatik xinxan nautilus
do
   qstat -a @$maquina
done > $temp

grep "^Request.*St$" $temp | uniq
grep "^-----.*--$" $temp | uniq
grep -v -e "^Request.*St$" -e "^-----.*--$" $temp

if [ `wc -l <$temp` != 0 ]
then
   echo
   total=0
   for status in Rrunning Qqueued Wwaiting
   do
      estat=${status#?}
      valor=`grep -c ${status%$estat}$ $temp`
      if [ $valor != 0 ]
      then
         if [ $total != 0 ]
         then
            echo -n ", "
         fi
         echo -n "$valor jobs $estat"
         total=1
      fi
   done
   echo
else
   echo No jobs
fi
echo

rm $temp
