#!/bin/bash

# fem du de cada directori, de tal manera que ens dona info de cada directori.
# la darrera linia es el total, i hi haura una linia que contindra el
# no_backup. restant-les, trobem el que es guarda

numero() {
   valor=$1
   if [ "$valor" = "" ]
   then
      valor=0
   fi
   while [ `echo $valor. | egrep -c '[0-9][0-9][0-9][0-9]\.'` = 1 ]
   do
      tmp=${valor%%???.*}
      valor=$tmp.${valor#$tmp}
   done
   printf "%13s " ${valor%.}
}

quotes() {
   rm -f /tmp/quota1 /tmp/quota2 2>/dev/null
   if [ $# = 0 ]
   then
      llista="/home/ug/* /home/um/*"
   else
      llista=""
      siug=0 # posare aixo a 1 si accepto usuaris ug
      sium=0 # posare aixo a 1 si accepto usuaris um
      for i in $*
      do
         if [ $i = ug ]
         then
            llista="$llista /home/ug/*"
            siug=1
         elif [ $i = um ]
         then
            llista="$llista /home/um/*"
            sium=1
         fi
      done
      while [ $# != 0 ]
      do
         if [ -d /home/ug/$1 ]
         then
            if [ $siug = 0 ]
            then
               llista="$llista /home/ug/$1"
            fi
         elif [ -d /home/um/$1 ]
         then
            if [ $sium = 0 ]
            then
               llista="$llista /home/um/$1"
            fi
         elif [ $1 != ug -a $1 != um ]
         then
            echo "Usuari $1 inexistent"
         fi
         shift
      done
   fi
   typeset -i numact numtot
   numact=1
   numtot=`ls -ld $llista | wc -l`
   for usuari in $llista
   do
      nom=${usuari##*/}
      grup=${usuari#/*/}
      grup=${grup%/$nom}
      echo -n Revisant usuari $nom \($numact/$numtot\)...
      cd $usuari/..
      du -k $usuari >/tmp/quota
      total=`tail -1 /tmp/quota | awk '{ print $1 }'`
      nobackuptmp=`awk '
         BEGIN { tot=0 }
         /\/no_backup$/ { tot=tot+$1 }
         /\/home\/u[gm]\/[^\/]+\/no_backup$/ { arrel=$1 }
         END { print tot"-"arrel }' /tmp/quota`
      nobackup=${nobackuptmp%-*}
      nobackuparrel=${nobackuptmp#*-}
      let resta=total-nobackup
      if [ `grep -c no_backup$ /tmp/quota` = 0 ]
      then
         numero $resta >>/tmp/quota1
         printf '            - ' >>/tmp/quota1
         printf '            - ' >>/tmp/quota1
         numero $total >>/tmp/quota1
         echo "$grup   $nom" >>/tmp/quota1
         echo $resta - $total $grup>>/tmp/quota2
      else
         numero $resta >>/tmp/quota1
         numero $nobackup >>/tmp/quota1
         numero $nobackuparrel >>/tmp/quota1
         numero $total >>/tmp/quota1
         echo "$grup   $nom" >>/tmp/quota1
         echo $resta $nobackup $total $grup>>/tmp/quota2
      fi
      echo " $total total, $resta backup"
      let numact=numact+1
   done
}

typeset -i total nobackup resta

if [ $# = 0 ]
then
   quotes
else
   quotes $*
fi

echo 'backup:    allo de que es fara backup' >/tmp/quota
echo 'no_backup: allo de que no es fara backup' >>/tmp/quota
echo 'arrel:     el no_backup de $HOME (allo que es pot moure al disc' >>/tmp/quota
echo '           local sense desorganitzar res)' >>/tmp/quota
echo 'total:     espai total ocupat al disc: backup+no_backup' >>/tmp/quota
echo >>/tmp/quota

echo '    backup      no_backup       arrel         total     grup usuari' >>/tmp/quota
echo '------------- ------------- ------------- ------------- ---- ---------' >>/tmp/quota
sort -r /tmp/quota1 >>/tmp/quota

echo '------------- ------------- ------------- ------------- ---- ---------' >>/tmp/quota
restat=`awk 'BEGIN { tot=0 } / ug$/ { tot=tot+$1 } END { print tot }' </tmp/quota2`
nobackupt=`awk 'BEGIN { tot=0 } / ug$/ { tot=tot+$2 } END { print tot }' </tmp/quota2`
totalt=`awk 'BEGIN { tot=0 } / ug$/ { tot=tot+$3 } END { print tot }' </tmp/quota2`
numero $restat >>/tmp/quota
numero $nobackupt >>/tmp/quota
printf '            - ' >>/tmp/quota
numero $totalt >>/tmp/quota
echo "total ug" >>/tmp/quota

restat=`awk 'BEGIN { tot=0 } / um$/ { tot=tot+$1 } END { print tot }' </tmp/quota2`
nobackupt=`awk 'BEGIN { tot=0 } / um$/ { tot=tot+$2 } END { print tot }' </tmp/quota2`
totalt=`awk 'BEGIN { tot=0 } / um$/ { tot=tot+$3 } END { print tot }' </tmp/quota2`
numero $restat >>/tmp/quota
numero $nobackupt >>/tmp/quota
printf '            - ' >>/tmp/quota
numero $totalt >>/tmp/quota
echo "total um" >>/tmp/quota

echo '------------- ------------- ------------- ------------- ---- ---------' >>/tmp/quota
restat=`awk 'BEGIN { tot=0 } { tot=tot+$1 } END { print tot }' </tmp/quota2`
nobackupt=`awk 'BEGIN { tot=0 } { tot=tot+$2 } END { print tot }' </tmp/quota2`
totalt=`awk 'BEGIN { tot=0 } { tot=tot+$3 } END { print tot }' </tmp/quota2`
numero $restat >>/tmp/quota
numero $nobackupt >>/tmp/quota
printf '            - ' >>/tmp/quota
numero $totalt >>/tmp/quota
echo TOTAL >>/tmp/quota

let restat=restat/1048576
let nobackupt=nobackupt/1048576
let totalt=totalt/1048576
printf "%10d Gb %10d Gb               %10d Gb aprox\n" $restat $nobackupt $totalt >>/tmp/quota

chown 2014:20 /tmp/quota
ara=`date +%Y%m%d-%H%M`
mv /tmp/quota /home/ug/ogonzalez/scripts/_LOGS/quota-$ara.txt
rm /tmp/quota?

