#!/bin/bash
#
# per definir facilment el DISPLAY mentre no trobem una alternativa millor
#
# sense parametres, mostra el valor actual (aixi m'estalvio de fer echo)
#
# amb parametres, agafa la maquina de $1 i la defineix com a DISPLAY.
# podem emprar "." per definir la "nostra" maquina
#
# per tal que quedi definit, s'ha de fer un source d'aquest script, aixi
# que defineixo un alias a profile per fer-ho. es diu 'd':
#
#	alias d='. (path)/setDISPLAY'
#

if [ $# != 0 ]
then

   if [ $1 = "." ]
   then
      jo=`whoami`
      maquina=`grep $jo - <<-EOF | awk '{ print $1 }'
         apolo      mburset
         basileia   eblanco
         cel        cchapple
         icarus     gparra
         kalamos    malba
         eidolon    ogonzalez oscar
         mar        rguigo roderic
         nautilus   fcamara
         rantanplan nbellora nicolas
         tmatik     scaste
         xinxan     jabril lopep
         zapiron    rcastelo
      EOF`
   else
      maquina=${1%:*}
      monitor=${1#$maquina}
      curt=${maquina%%.*}
      case $curt in
         a*)  maquina=apolo
              ;;
         b*)  maquina=basileia
              ;;
         c*)  maquina=cel
              ;;
         e*)  maquina=eidolon
              ;;
         i*)  maquina=icarus
              ;;
         ka*) maquina=kalamos
              ;;
         k*)  maquina=korax
              ;;
         m*1) maquina=monstre1
              ;;
         m*2) maquina=monstre2
              ;;
         m*3) maquina=monstre3
              ;;
         m*4) maquina=monstre4
              ;;
         m*)  maquina=mar
              ;;
         n*)  maquina=nautilus
              ;;
         r*)  maquina=rantanplan
              ;;
         tr*) maquina=tro
              ;;
         t*)  maquina=tmatik
              ;;
         x*)  maquina=xinxan
              ;;
         z*)  maquina=zapiron
              ;;
         *)   unset maquina
              ;;
      esac
   fi

   if [ ${monitor:-def} = def ]
   then
      monitor=:0.0
   fi

   if [ `hostname -s` = $maquina ]
   then
      maquina=""
   fi

   export DISPLAY=$maquina$monitor
   unset maquina monitor

   # guardo DISPLAY a $HOME/.rdisplay per emprar-lo des d'altres maquines
   echo $DISPLAY >$HOME/.rdisplay

fi

if [ "${DISPLAY%:*}" = "" ]
then
   echo "DISPLAY=(`hostname -s`)$DISPLAY"
else
   echo DISPLAY=$DISPLAY
fi

