#!/bin/sh
#
# Literate Programming for "sgp2.nw"
#
# $Id: aol,v 1.5 2000-10-19 11:22:57 jabril Exp $

# defining variables
NWdir="."
BINdir="../bin"
DOCdir="../docs"

# extracting SGP2 program lines 
notangle -L -Rsgp2.pl $NWdir/sgp2.nw | \
perl -ne '$. > 2  && do { print; next };
          $. == 1 && do {
                  split / /, $_, 3;
                  $n = "$_[0] ".(++$_[1])." $_[2]"
          };
          $. == 2 && ( print "$_$n" );' > $BINdir/sgp2.pl

# extracting TEST program lines 
notangle -Rrunsgp2-a.sh $NWdir/sgp2.nw > $BINdir/runsgp2-a.sh
notangle -Rrunsgp1-a.sh $NWdir/sgp2.nw > $BINdir/runsgp1-a.sh

# making executables
chmod a+x $BINdir/sgp2.pl $BINdir/runsgp2-a.sh $BINdir/runsgp1-a.sh

# extracting CONFIG files 
notangle -Rsgp2-gff2ps.rc $NWdir/sgp2.nw > $BINdir/param/sgp2-gff2ps.rc
notangle -Rsgp2-aplot.rc  $NWdir/sgp2.nw > $BINdir/param/sgp2-aplot.rc

# extracting program documentation
noweave -delay -index $NWdir/sgp2.nw > $DOCdir/sgp2.tex
cd $DOCdir
latex sgp2.tex ; latex sgp2.tex ; latex sgp2.tex ; dvips sgp2.dvi -o sgp2.ps
