#!/bin/sh
#
# Literate Programming for "sgp2.nw"
#
# $Id: aol,v 1.4 2000-10-16 17:55:10 jabril Exp $

# defining variables
NWdir="."
BINdir="../bin"
DOCdir="../docs"

# extracting program lines 
notangle -L -Rsgp2.pl $NWdir/sgp2.nw > $BINdir/sgp2.tmp
perl -ne '($. > 2) && do { print; next }; $. == 1 && do { split / /, $_, 3; $n = "$_[0] ".(++$_[1])." $_[2]"}; $. == 2 && ( print "$_$n" );' $BINdir/sgp2.tmp > $BINdir/sgp2.pl

# extracting program lines 
notangle -Rrunsgp2-a.sh $NWdir/sgp2.nw > $BINdir/runsgp2-a.sh

# extracting program documentation
noweave -delay -index $NWdir/sgp2.nw > $DOCdir/sgp2.tex
cd $DOCdir
latex sgp2.tex ; latex sgp2.tex ; latex sgp2.tex ; dvips sgp2.dvi -o sgp2.ps
